import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { FileText, Download, Calendar, Filter, Sparkles } from 'lucide-react';
import { Card } from '../components/UI/Card';
import { Button } from '../components/UI/Button';
import { Table } from '../components/UI/Table';
import jsPDF from 'jspdf';

const Reports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState('attendance');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const response = await axios.get('http://localhost:5000/api/reports');
      setReports(response.data);
    } catch (error) {
      console.error('Error fetching reports:', error);
    }
  };

  const generateReport = async () => {
    setGenerating(true);
    try {
      let response;
      if (reportType === 'attendance') {
        response = await axios.post('http://localhost:5000/api/reports/attendance', {
          startDate: '2024-10-01',
          endDate: '2024-10-31',
          class: '10A'
        });
      } else if (reportType === 'performance') {
        response = await axios.post('http://localhost:5000/api/reports/performance', {
          studentId: 'STU001',
          semester: 'Fall 2024'
        });
      } else {
        response = await axios.post('http://localhost:5000/api/reports/ai-summary', {
          type: 'general',
          data: {}
        });
      }
      
      alert(`Report generated successfully! ID: ${response.data.reportId}`);
      fetchReports();
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const downloadPDF = (report: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235); // Blue color
    doc.text('EduAdmin AI - Report', 20, 20);
    
    // Report details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Report Title: ${report.title}`, 20, 40);
    doc.text(`Type: ${report.type}`, 20, 50);
    doc.text(`Generated: ${report.date}`, 20, 60);
    doc.text(`Status: ${report.status}`, 20, 70);
    
    // Divider
    doc.setLineWidth(0.5);
    doc.line(20, 75, 190, 75);
    
    // Content
    doc.setFontSize(14);
    doc.text('Report Summary', 20, 85);
    doc.setFontSize(10);
    const content = [
      'This is a sample generated report from EduAdmin AI platform.',
      '',
      'Key Findings:',
      '• Overall attendance rate: 92%',
      '• Average student performance: 85%',
      '• Number of at-risk students: 5',
      '',
      'Recommendations:',
      '1. Implement personalized tutoring for at-risk students',
      '2. Continue monitoring attendance patterns',
      '3. Recognize top performers with awards',
    ];
    
    let yPos = 95;
    content.forEach(line => {
      doc.text(line, 20, yPos);
      yPos += 7;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by EduAdmin AI Platform', 20, 280);
    doc.text(`Report ID: ${report.id}`, 20, 285);
    
    // Save the PDF
    doc.save(`${report.title.replace(/\s+/g, '_')}_${report.id}.pdf`);
  };

  const exportAllAsPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text('EduAdmin AI - All Reports', 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.text(`Total Reports: ${reports.length}`, 20, 37);
    
    doc.setLineWidth(0.5);
    doc.line(20, 42, 190, 42);
    
    let yPos = 50;
    reports.forEach((report, index) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(12);
      doc.setTextColor(37, 99, 235);
      doc.text(`${index + 1}. ${report.title}`, 20, yPos);
      
      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      doc.text(`Type: ${report.type} | Date: ${report.date} | Status: ${report.status}`, 25, yPos + 6);
      
      yPos += 15;
    });
    
    doc.save(`all_reports_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const columns = [
    { key: 'id', label: 'ID' },
    { key: 'title', label: 'Report Title' },
    {
      key: 'type',
      label: 'Type',
      render: (type: string) => (
        <span className="px-2 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 rounded text-xs font-medium">
          {type}
        </span>
      )
    },
    { key: 'date', label: 'Generated Date' },
    {
      key: 'status',
      label: 'Status',
      render: (status: string) => (
        <span className="px-2 py-1 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded text-xs font-medium">
          {status}
        </span>
      )
    },
    {
      key: 'actions',
      label: 'Actions',
      render: (_: any, report: any) => (
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={() => downloadPDF(report)}>
            <Download className="w-4 h-4" />
            Download
          </Button>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          Report Generation
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          Generate and manage AI-powered reports
        </p>
      </div>

      {/* Generate New Report */}
      <Card title="Generate New Report">
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Report Type
              </label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="w-full px-4 py-2 bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-gray-900 dark:text-white"
              >
                <option value="attendance">Attendance Report</option>
                <option value="performance">Performance Report</option>
                <option value="ai-summary">AI Summary Report</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Start Date
              </label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="date"
                  className="w-full pl-10 pr-4 py-2 bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-gray-900 dark:text-white"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                End Date
              </label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="date"
                  className="w-full pl-10 pr-4 py-2 bg-gray-50 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </div>

          <div className="flex gap-2">
            <Button onClick={generateReport} disabled={generating}>
              {generating ? (
                <>Generating...</>
              ) : (
                <>
                  <FileText className="w-5 h-5" />
                  Generate Report
                </>
              )}
            </Button>
            <Button variant="outline">
              <Filter className="w-5 h-5" />
              Advanced Options
            </Button>
          </div>
        </div>
      </Card>

      {/* Previous Reports */}
      <Card title="Previous Reports">
        <Table columns={columns} data={reports} />
      </Card>

      {/* AI Report Templates */}
      <Card title="AI-Powered Report Templates">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg hover:border-blue-500 dark:hover:border-blue-500 transition-colors cursor-pointer">
            <Sparkles className="w-8 h-8 text-blue-600 dark:text-blue-400 mb-3" />
            <h4 className="font-semibold text-gray-900 dark:text-white mb-2">
              Student Progress Report
            </h4>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              AI-generated comprehensive student performance analysis
            </p>
          </div>

          <div className="p-4 border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg hover:border-green-500 dark:hover:border-green-500 transition-colors cursor-pointer">
            <Sparkles className="w-8 h-8 text-green-600 dark:text-green-400 mb-3" />
            <h4 className="font-semibold text-gray-900 dark:text-white mb-2">
              Class Analytics Report
            </h4>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Detailed class-level performance and attendance trends
            </p>
          </div>

          <div className="p-4 border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg hover:border-purple-500 dark:hover:border-purple-500 transition-colors cursor-pointer">
            <Sparkles className="w-8 h-8 text-purple-600 dark:text-purple-400 mb-3" />
            <h4 className="font-semibold text-gray-900 dark:text-white mb-2">
              Risk Assessment Report
            </h4>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              AI predictions for at-risk students with interventions
            </p>
          </div>
        </div>
      </Card>

      {/* Export Options */}
      <Card title="Export Options">
        <div className="flex flex-wrap gap-3">
          <Button variant="outline" onClick={exportAllAsPDF}>
            <Download className="w-5 h-5" />
            Export as PDF
          </Button>
          <Button variant="outline" onClick={() => alert('Excel export: Feature coming soon!')}>
            <Download className="w-5 h-5" />
            Export as Excel
          </Button>
          <Button variant="outline" onClick={() => {
            const csv = reports.map(r => `${r.id},${r.title},${r.type},${r.date},${r.status}`).join('\n');
            const blob = new Blob([`ID,Title,Type,Date,Status\n${csv}`], { type: 'text/csv' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `reports_${new Date().toISOString().split('T')[0]}.csv`;
            a.click();
            window.URL.revokeObjectURL(url);
          }}>
            <Download className="w-5 h-5" />
            Export as CSV
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default Reports;
